// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/engytita/engytita-operator/pkg/clientset/versioned"
	cachev1alpha1 "github.com/engytita/engytita-operator/pkg/clientset/versioned/typed/cache/v1alpha1"
	fakecachev1alpha1 "github.com/engytita/engytita-operator/pkg/clientset/versioned/typed/cache/v1alpha1/fake"
	cacheregionv1alpha1 "github.com/engytita/engytita-operator/pkg/clientset/versioned/typed/cacheregion/v1alpha1"
	fakecacheregionv1alpha1 "github.com/engytita/engytita-operator/pkg/clientset/versioned/typed/cacheregion/v1alpha1/fake"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var (
	_ clientset.Interface = &Clientset{}
	_ testing.FakeClient  = &Clientset{}
)

// CacheV1alpha1 retrieves the CacheV1alpha1Client
func (c *Clientset) CacheV1alpha1() cachev1alpha1.CacheV1alpha1Interface {
	return &fakecachev1alpha1.FakeCacheV1alpha1{Fake: &c.Fake}
}

// CacheregionV1alpha1 retrieves the CacheregionV1alpha1Client
func (c *Clientset) CacheregionV1alpha1() cacheregionv1alpha1.CacheregionV1alpha1Interface {
	return &fakecacheregionv1alpha1.FakeCacheregionV1alpha1{Fake: &c.Fake}
}
