// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/engytita/engytita-operator/api/v1alpha1"
	scheme "github.com/engytita/engytita-operator/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CachesGetter has a method to return a CacheInterface.
// A group's client should implement this interface.
type CachesGetter interface {
	Caches(namespace string) CacheInterface
}

// CacheInterface has methods to work with Cache resources.
type CacheInterface interface {
	Create(ctx context.Context, cache *v1alpha1.Cache, opts v1.CreateOptions) (*v1alpha1.Cache, error)
	Update(ctx context.Context, cache *v1alpha1.Cache, opts v1.UpdateOptions) (*v1alpha1.Cache, error)
	UpdateStatus(ctx context.Context, cache *v1alpha1.Cache, opts v1.UpdateOptions) (*v1alpha1.Cache, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Cache, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.CacheList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Cache, err error)
	CacheExpansion
}

// caches implements CacheInterface
type caches struct {
	client rest.Interface
	ns     string
}

// newCaches returns a Caches
func newCaches(c *CacheV1alpha1Client, namespace string) *caches {
	return &caches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the cache, and returns the corresponding cache object, and an error if there is any.
func (c *caches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Cache, err error) {
	result = &v1alpha1.Cache{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("caches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Caches that match those selectors.
func (c *caches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CacheList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.CacheList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("caches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested caches.
func (c *caches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("caches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a cache and creates it.  Returns the server's representation of the cache, and an error, if there is any.
func (c *caches) Create(ctx context.Context, cache *v1alpha1.Cache, opts v1.CreateOptions) (result *v1alpha1.Cache, err error) {
	result = &v1alpha1.Cache{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("caches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cache).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a cache and updates it. Returns the server's representation of the cache, and an error, if there is any.
func (c *caches) Update(ctx context.Context, cache *v1alpha1.Cache, opts v1.UpdateOptions) (result *v1alpha1.Cache, err error) {
	result = &v1alpha1.Cache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("caches").
		Name(cache.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cache).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *caches) UpdateStatus(ctx context.Context, cache *v1alpha1.Cache, opts v1.UpdateOptions) (result *v1alpha1.Cache, err error) {
	result = &v1alpha1.Cache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("caches").
		Name(cache.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(cache).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the cache and deletes it. Returns an error if one occurs.
func (c *caches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("caches").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *caches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("caches").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched cache.
func (c *caches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Cache, err error) {
	result = &v1alpha1.Cache{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("caches").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
