// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/engytita/engytita-operator/pkg/clientset/versioned/typed/cache/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCacheV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCacheV1alpha1) Caches(namespace string) v1alpha1.CacheInterface {
	return &FakeCaches{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCacheV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
