// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/engytita/engytita-operator/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCacheRegions implements CacheRegionInterface
type FakeCacheRegions struct {
	Fake *FakeCacheregionV1alpha1
	ns   string
}

var cacheregionsResource = schema.GroupVersionResource{Group: "cacheregion", Version: "v1alpha1", Resource: "cacheregions"}

var cacheregionsKind = schema.GroupVersionKind{Group: "cacheregion", Version: "v1alpha1", Kind: "CacheRegion"}

// Get takes name of the cacheRegion, and returns the corresponding cacheRegion object, and an error if there is any.
func (c *FakeCacheRegions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CacheRegion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(cacheregionsResource, c.ns, name), &v1alpha1.CacheRegion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CacheRegion), err
}

// List takes label and field selectors, and returns the list of CacheRegions that match those selectors.
func (c *FakeCacheRegions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CacheRegionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(cacheregionsResource, cacheregionsKind, c.ns, opts), &v1alpha1.CacheRegionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CacheRegionList{ListMeta: obj.(*v1alpha1.CacheRegionList).ListMeta}
	for _, item := range obj.(*v1alpha1.CacheRegionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cacheRegions.
func (c *FakeCacheRegions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(cacheregionsResource, c.ns, opts))

}

// Create takes the representation of a cacheRegion and creates it.  Returns the server's representation of the cacheRegion, and an error, if there is any.
func (c *FakeCacheRegions) Create(ctx context.Context, cacheRegion *v1alpha1.CacheRegion, opts v1.CreateOptions) (result *v1alpha1.CacheRegion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(cacheregionsResource, c.ns, cacheRegion), &v1alpha1.CacheRegion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CacheRegion), err
}

// Update takes the representation of a cacheRegion and updates it. Returns the server's representation of the cacheRegion, and an error, if there is any.
func (c *FakeCacheRegions) Update(ctx context.Context, cacheRegion *v1alpha1.CacheRegion, opts v1.UpdateOptions) (result *v1alpha1.CacheRegion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(cacheregionsResource, c.ns, cacheRegion), &v1alpha1.CacheRegion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CacheRegion), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCacheRegions) UpdateStatus(ctx context.Context, cacheRegion *v1alpha1.CacheRegion, opts v1.UpdateOptions) (*v1alpha1.CacheRegion, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(cacheregionsResource, "status", c.ns, cacheRegion), &v1alpha1.CacheRegion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CacheRegion), err
}

// Delete takes name of the cacheRegion and deletes it. Returns an error if one occurs.
func (c *FakeCacheRegions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(cacheregionsResource, c.ns, name, opts), &v1alpha1.CacheRegion{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCacheRegions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(cacheregionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CacheRegionList{})
	return err
}

// Patch applies the patch and returns the patched cacheRegion.
func (c *FakeCacheRegions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CacheRegion, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(cacheregionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.CacheRegion{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CacheRegion), err
}
